### ISSUE TITLE
VALIDADE QR CODE

### ISSUE THREAD

**Issue by leanndisfarce** [InCuca/pix-for-woocommerce#10]
Instalei vosso plugin porem o QR CODE que ele geral não é valido, aí o cliente não consegue gerar o pagamento do PIX.

**Comment by samoaste** [comment]
oi @leanndisfarce, ele é válido. Normalmente é alguma configuração no cadastro das informações que ficou incorreta. Lá no fórum de suporte do plugin tem várias dicas: https://wordpress.org/support/plugin/incuca-tech-pix-for-woocommerce/
