### ISSUE TITLE
Imagem do QR Code não aparece na tela de pagamento do Pix

### ISSUE THREAD

**Issue by seo-antonioduarte** [InCuca/pix-for-woocommerce#13]
Olá Senhores

O QR Code não aparece na tela de pagemtno da minha instação de Wooocommerce. Não tenho certeza, mas, como aparece no e-mail e em outro site que está em um provedor "barato", acredito que seja um problema no Firewall que está bloqueando.

Podem me ajudar? Qual seria a porta, o Protocolo e o(s) IP(s) que tenho que liberar no meu Firewall para conseguir a imagem. Se não for isso, alguém tem uma idéia do que pode ser?

Caso alguém queira testar, o site que estrou construindo tem um produto corretamente cadastrado. Basta comprar 3 unidades ou mais por conta do valor do pedido mínimo, e colocar qualquer e-mail na hora que for solicitado, não precisa ser real.

O produto configurado está em [https://dakidaeuropa.com.br/beleza-e-perfumaria/facial/anti-idade/serum-anti-idade-rejuvenescimento-facial-exclusive-european-filmexel/](https://dakidaeuropa.com.br/beleza-e-perfumaria/facial/anti-idade/serum-anti-idade-rejuvenescimento-facial-exclusive-european-filmexel/)

Agradeço toda e qualquer ajuda.

**Comment by samoaste** [comment]
Só desativar o lazyload do Jetpack e usar de outro plugin, tipo o https://br.wordpress.org/plugins/rocket-lazy-load/. O Jetpack da problema com imagens em base64.

**Comment by seo-antonioduarte** [comment]
Perfeito! Resolvido! Muito obrigado Samuel!!!
