### ISSUE TITLE
Travou todo WooCommerce e bugou checkout

### ISSUE THREAD

**Issue by sergioLemosB** [InCuca/pix-for-woocommerce#18]
WordPress 6.1.1 com WP Astra Pro 3.9.3 e WooCommerce 7.10

Gera um grande erro no checkout e não abre o InCuca Tech - Pix for WooCommerce (desaparce na finalização da compra)
Ao desativar consegue finalizar normalmente por outros meios. 

O Bug é gigante!

**Comment by samoaste** [comment]
@sergioLemosB você possui um ambiente para testes?
Com o Astra na versão gratuita não há conflito.
