### ISSUE TITLE
Plugin não está gerando o QR Code

### ISSUE THREAD

**Issue by gersbandfilho** [InCuca/pix-for-woocommerce#7]
Olá, instalei o plugin em minha loja seguindo todos os passos porém o QR Code não está sendo gerado.

Como devo proceder?

www.bilharmais.com.br

![image](https://user-images.githubusercontent.com/83312417/119136204-c2c98b80-ba15-11eb-9370-8a49c9f99449.png)

**Comment by samoaste** [comment]
@gersbandfilho desativa o lazy load do Jetpack. Ele causa conflito na imagem do QR Code. Você pode usar esse plugin para lazy load no lugar: https://wordpress.org/plugins/rocket-lazy-load/

**Comment by gersbandfilho** [comment]
Olá! Certo, começou a gerar o QR Code, muito obrigado.

Aconteceu outro problema mas abrirei outro tópico para não confundir quem vier buscar este problema posteriormente.

Grato!
